sudo: required


services:
  - docker

before_install:
  - docker pull xacc/base-plugin-ci
  - docker run -it --rm xacc/base-plugin-ci bash -c "git clone https://github.com/ornl-qci/xacc-rigetti && cd xacc-rigetti && mkdir build && cd build && cmake .. -DXACC_DIR=~/.xacc -DRIGETTI_BUILD_TESTS=TRUE && make -j4 install && ctest"
script:
  - echo ""
